const API_URL='https://compliance-api-production-dd13.up.railway.app';
const SUPABASE_URL='https://pbprkgkvsxkpdhsmjzrc.supabase.co';
const SUPABASE_KEY='sb_publishable_UBCXWvPIRsU1SLpwZzGvig_dSIJYSjO';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let pendingPlan=null;let authMode='signin';let checkoutStarting=false;
const AUTH_REDIRECT=location.origin+'/';

function openModal(id){document.getElementById(id)?.classList.add('open')}
function closeModal(id){document.getElementById(id)?.classList.remove('open')}
function setStatus(el,message,isError=false){if(!el)return;el.textContent=message||'';el.className=el.className.replace(/\s?(show|error)/g,'').trim();if(message)el.classList.add('show');if(isError)el.classList.add('error')}
function riskLabel(v){return v==='professional_review_advised'?'Professional review advised':v==='review_recommended'?'Review recommended':'Informational'}
function riskClass(v){return v==='professional_review_advised'?'pro':v==='review_recommended'?'review':''}
function fmtDate(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function safeUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

async function getSession(){const {data}=await sb.auth.getSession();return data?.session||null}
async function refreshSessionUI(){const session=await getSession();const pill=document.getElementById('sessionPill');const login=document.getElementById('loginBtn');if(session?.user){document.getElementById('sessionEmail').textContent=session.user.email||'Signed in';pill.classList.add('show');login.classList.add('hidden')}else{pill.classList.remove('show');login.classList.remove('hidden')}return session}

function switchAuth(mode){authMode=mode;const signIn=mode==='signin';document.getElementById('authSignInTab').classList.toggle('active',signIn);document.getElementById('authSignUpTab').classList.toggle('active',!signIn);document.getElementById('authSubmit').textContent=signIn?'Sign in →':'Create account →';document.getElementById('authPassword').autocomplete=signIn?'current-password':'new-password';document.getElementById('authResend').classList.toggle('hidden',signIn);setStatus(document.getElementById('authStatus'),'')}
function showAuth(plan=null,mode='signin'){pendingPlan=plan;if(plan)localStorage.setItem('ba_pending_plan',plan);switchAuth(mode);document.getElementById('authCopy').textContent=plan?'Sign in or create your account. We will continue to secure Stripe Checkout after authentication.':'Sign in or create your BrandedAlign account.';openModal('authModal');setTimeout(()=>document.getElementById('authEmail').focus(),50)}

async function beginCheckout(planKey){pendingPlan=planKey;const session=await getSession();if(!session?.access_token){showAuth(planKey,'signin');return}if(checkoutStarting)return;checkoutStarting=true;const btns=[...document.querySelectorAll(`.plan-btn[data-plan="${planKey}"]`)];btns.forEach(b=>b.classList.add('checkout-loading'));try{const r=await fetch(API_URL+'/billing/checkout-session',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({plan_key:planKey})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||d.message||'Unable to create Stripe Checkout.');const url=d.url||d.checkout_url||d.checkoutUrl;if(!url)throw new Error('Stripe Checkout did not return a checkout URL.');window.location.assign(url)}catch(err){checkoutStarting=false;btns.forEach(b=>b.classList.remove('checkout-loading'));alert(err?.message||'Unable to start checkout.')}}

async function openBilling(){const session=await getSession();if(!session?.access_token){showAuth(null,'signin');return}try{const r=await fetch(API_URL+'/billing/portal-session',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:'{}'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||d.message||'Unable to open billing portal.');const url=d.url||d.portal_url||d.portalUrl;if(!url)throw new Error('Billing portal did not return a URL.');window.location.assign(url)}catch(err){alert(err?.message||'Unable to open billing portal.')}}

async function runFitCheck(e){e.preventDefault();const btn=document.getElementById('fitBtn');const out=document.getElementById('fitResult');const url=document.getElementById('fitUrl').value.trim();btn.disabled=true;btn.textContent='Checking…';out.className='result-box';out.textContent='';try{const r=await fetch(API_URL+'/discovery/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||d.message||'The Fit Check could not be completed.');const score=d.score??d.overall_score??d.summary?.score;const pages=d.pages_scanned??d.summary?.pages_scanned??d.page_count;const findings=d.findings??d.top_findings??d.issues??[];let html='<strong>Fit Check complete'+(score!=null?' · '+esc(score):'')+'</strong>';if(pages!=null)html+='<div style="margin-top:5px">'+esc(pages)+' page(s) reviewed.</div>';if(Array.isArray(findings)&&findings.length){html+='<ul>'+findings.slice(0,5).map(x=>'<li>'+esc(x.title||x.message||x.name||'Potential issue')+'</li>').join('')+'</ul>'}else{html+='<div style="margin-top:8px">No finding details were returned by this quick check.</div>'}out.innerHTML=html;out.classList.add('show')}catch(err){out.textContent=err?.message||'The Fit Check could not be completed.';out.classList.add('show','error')}finally{btn.disabled=false;btn.textContent='Check this page →'}}

function renderDive(d){const card=document.createElement('article');card.className='deep-card';card.innerHTML=`<div class="deep-meta"><span class="deep-tag">${esc(d.category||'Deep Dive')}</span><span class="deep-tag ${riskClass(d.risk_level)}">${esc(riskLabel(d.risk_level))}</span></div><h3>${esc(d.title||'Deep Dive')}</h3><p>${esc(d.summary||'')}</p><div class="takeaway">${esc(d.safe_takeaway||'Review the source and use qualified advice when the stakes are high.')}</div><div class="deep-actions"><button type="button" class="link-btn">Read Deep Dive →</button><span class="reviewed">${d.reviewed_at?'Reviewed '+esc(fmtDate(d.reviewed_at)):''}</span></div>`;card.querySelector('.link-btn').addEventListener('click',()=>openDive(d));return card}
function openDive(d){const src=safeUrl(d.source_url);const paragraphs=String(d.body||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('');document.getElementById('diveContent').innerHTML=`<span class="eyebrow">${esc(d.category||'Deep Dive')}</span><h2 id="diveTitle">${esc(d.title||'Deep Dive')}</h2><p><strong>${esc(riskLabel(d.risk_level))}</strong>${d.reviewed_at?' · Reviewed '+esc(fmtDate(d.reviewed_at)):''}</p>${paragraphs}<div class="takeaway" style="margin-top:18px">Safer takeaway: ${esc(d.safe_takeaway||'Review the source and use qualified advice when the stakes are high.')}</div>${src?`<p><a class="source-link" href="${esc(src)}" target="_blank" rel="noopener noreferrer">Primary source: ${esc(d.source_label||src)} →</a></p>`:''}<p style="font-size:12px">This Deep Dive is educational guidance, not legal advice or a guarantee of compliance.</p>`;openModal('diveModal')}
async function loadDeepDives(){const grid=document.getElementById('deepGrid');try{const {data,error}=await sb.from('deep_dives').select('slug,title,summary,body,safe_takeaway,category,risk_level,source_label,source_url,source_type,reviewed_at,display_order,published_at').eq('published',true).order('display_order',{ascending:true}).order('published_at',{ascending:false});if(error)throw error;grid.textContent='';if(!data?.length){grid.innerHTML='<div class="deep-empty">Deep Dives are being reviewed for publication.</div>';return}data.forEach(d=>grid.appendChild(renderDive(d)))}catch(err){grid.innerHTML='<div class="deep-empty">Deep Dives are temporarily unavailable. Check back after the next content review.</div>';console.error('Deep Dives failed to load',err)}}

function handleReturnMessage(){const p=new URLSearchParams(location.search);const success=['success','complete','completed'].includes((p.get('billing')||p.get('checkout')||'').toLowerCase())||p.get('success')==='true';const cancel=['cancel','canceled','cancelled'].includes((p.get('billing')||p.get('checkout')||'').toLowerCase());if(success)setTimeout(()=>alert('Stripe returned you to BrandedAlign. Access is unlocked only after the verified webhook updates your subscription state.'),300);else if(cancel)setTimeout(()=>alert('Checkout was canceled. No paid access was unlocked.'),300)}
function handleAuthReturn(){const h=new URLSearchParams(location.hash.replace(/^#/,''));const code=h.get('error_code');if(!code)return;const description=(h.get('error_description')||'The email confirmation link could not be used.').replace(/\+/g,' ');showAuth(localStorage.getItem('ba_pending_plan')||null,'signup');setStatus(document.getElementById('authStatus'),code==='otp_expired'?'That confirmation link expired. Enter your email and click “Resend confirmation email,” then use the newest link.':description,true)}

document.querySelectorAll('.plan-btn').forEach(b=>b.addEventListener('click',()=>beginCheckout(b.dataset.plan)));
document.getElementById('fitForm').addEventListener('submit',runFitCheck);
document.getElementById('loginBtn').addEventListener('click',()=>showAuth(null,'signin'));
document.getElementById('footerLoginBtn').addEventListener('click',()=>showAuth(null,'signin'));
document.getElementById('billingBtn').addEventListener('click',openBilling);
document.getElementById('legalBtn').addEventListener('click',()=>openModal('legalModal'));
document.getElementById('authSignInTab').addEventListener('click',()=>switchAuth('signin'));
document.getElementById('authSignUpTab').addEventListener('click',()=>switchAuth('signup'));
document.getElementById('signOutBtn').addEventListener('click',async()=>{await sb.auth.signOut();await refreshSessionUI()});
document.getElementById('authForm').addEventListener('submit',async e=>{e.preventDefault();const st=document.getElementById('authStatus');const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;if(!email||password.length<8){setStatus(st,'Enter a valid email and a password of at least 8 characters.',true);return}setStatus(st,authMode==='signin'?'Signing in…':'Creating your account…');try{if(authMode==='signin'){const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;setStatus(st,'Signed in.');closeModal('authModal');await refreshSessionUI();if(pendingPlan){const p=pendingPlan;pendingPlan=null;localStorage.removeItem('ba_pending_plan');await beginCheckout(p)}}else{const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:AUTH_REDIRECT}});if(error)throw error;if(data?.session){setStatus(st,'Account created and signed in.');closeModal('authModal');await refreshSessionUI();if(pendingPlan){const p=pendingPlan;pendingPlan=null;localStorage.removeItem('ba_pending_plan');await beginCheckout(p)}}else{document.getElementById('authResend').classList.remove('hidden');setStatus(st,'Account created. Check your email and confirm it. The confirmation link will return you to BrandedAlign, then your selected plan can continue to checkout.')}}}catch(err){setStatus(st,err?.message||'Authentication failed.',true)}});
document.getElementById('authResend').addEventListener('click',async()=>{const st=document.getElementById('authStatus');const email=document.getElementById('authEmail').value.trim();if(!email){setStatus(st,'Enter the email address you used for the account.',true);return}setStatus(st,'Sending a new confirmation email…');try{const {error}=await sb.auth.resend({type:'signup',email,options:{emailRedirectTo:AUTH_REDIRECT}});if(error)throw error;setStatus(st,'New confirmation email sent. Use the newest link in your inbox.')}catch(err){setStatus(st,err?.message||'Unable to resend the confirmation email.',true)}});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>m.classList.remove('open'))});
document.querySelectorAll('.faq button').forEach(b=>b.addEventListener('click',()=>b.closest('.faq').classList.toggle('open')));
sb.auth.onAuthStateChange(async(_event,session)=>{await refreshSessionUI();if(session?.access_token){const saved=localStorage.getItem('ba_pending_plan');if(saved){localStorage.removeItem('ba_pending_plan');pendingPlan=null;setTimeout(()=>beginCheckout(saved),150)}}});
refreshSessionUI().then(async session=>{if(session?.access_token){const saved=localStorage.getItem('ba_pending_plan');if(saved){localStorage.removeItem('ba_pending_plan');await beginCheckout(saved)}}});loadDeepDives();handleReturnMessage();handleAuthReturn();