const http=require('http');
const fs=require('fs');
const path=require('path');
const port=Number(process.env.PORT||8080);
const root=__dirname;
const commonHeaders={
  'X-Content-Type-Options':'nosniff',
  'Referrer-Policy':'strict-origin-when-cross-origin',
  'X-Frame-Options':'SAMEORIGIN',
  'Permissions-Policy':'camera=(), microphone=(), geolocation=()',
  'Content-Security-Policy':"default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; connect-src 'self' https://pbprkgkvsxkpdhsmjzrc.supabase.co https://compliance-api-production-dd13.up.railway.app; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'self'; base-uri 'self'; form-action 'self' https://checkout.stripe.com"
};
const launchStyles=`<style id="launch-luxury-v3">
body{background:
radial-gradient(circle at 7% 8%,rgba(171,235,232,.28),transparent 28%),
radial-gradient(circle at 94% 12%,rgba(236,197,129,.30),transparent 27%),
radial-gradient(circle at 82% 63%,rgba(224,176,165,.17),transparent 24%),
linear-gradient(180deg,#fffdfa 0%,#fbf4e8 52%,#f5faf6 100%)!important}
.site-header{background:rgba(255,253,248,.94)!important;box-shadow:0 8px 28px rgba(18,43,57,.05)}
.nav{height:88px!important}.brand-mark{border-radius:50%!important;background:radial-gradient(circle at 35% 28%,#1f4b59,#102b38 70%)!important;box-shadow:0 10px 26px rgba(18,43,57,.20),inset 0 0 0 1px rgba(255,255,255,.12)!important}
.hero{padding:68px 0 42px!important;min-height:690px;background:
radial-gradient(circle at 69% 24%,rgba(255,245,219,.74),transparent 28%),
radial-gradient(circle at 17% 76%,rgba(198,238,236,.30),transparent 30%),
linear-gradient(115deg,rgba(255,255,255,.44),rgba(255,251,243,.12))}
.hero-grid{grid-template-columns:1.03fr .97fr!important;gap:22px!important}.hero h1{font-size:clamp(62px,6.4vw,98px)!important;max-width:690px}.hero h1 span{background:linear-gradient(105deg,#0d7183 0%,#2aa4ae 34%,#7d9f78 65%,#d09639 100%)!important;-webkit-background-clip:text!important;background-clip:text!important;color:transparent!important}.hero p{font-size:18px!important;max-width:640px!important}.hero-actions{grid-template-columns:repeat(3,minmax(0,1fr))!important;max-width:760px!important;gap:13px!important}.hero-choice{min-height:136px!important;padding:22px 20px!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:center!important;border-radius:20px!important;background:rgba(255,255,255,.82)!important;backdrop-filter:blur(12px);box-shadow:0 18px 46px rgba(18,43,57,.09)!important}.hero-choice.audit{background:linear-gradient(180deg,rgba(255,250,248,.94),rgba(247,235,231,.82))!important}.hero-choice.fit{background:linear-gradient(180deg,rgba(255,249,235,.96),rgba(246,230,198,.78))!important}.hero-choice-icon{width:48px!important;height:48px!important;border-radius:50%!important;margin-bottom:10px;background:linear-gradient(145deg,#fff,#edf8f6)!important}.hero-choice.fit .hero-choice-icon{color:#8d641f!important;background:linear-gradient(145deg,#fff9eb,#f2d89f)!important}.hero-choice strong{font-size:22px!important}.hero-choice small{font-size:9px!important}.hero-choice:after{right:16px!important;top:18px!important;transform:none!important}.hero-fit-link{display:none!important}.hero-art{min-height:610px!important}.orb-stage{width:min(43vw,590px)!important;height:min(43vw,590px)!important;filter:drop-shadow(0 34px 54px rgba(26,49,52,.16)) drop-shadow(0 0 34px rgba(220,175,89,.11))!important}.trust-band{padding:18px 0 54px!important}.trust-row{background:rgba(255,255,255,.70)!important;border:1px solid rgba(199,155,85,.18)!important;box-shadow:0 24px 60px rgba(18,43,57,.07)!important}.trust-row:before{background:#fbf7ef!important;color:#0d6871!important}.trust-icon{background:linear-gradient(145deg,#fff7df,#e8c574)!important;box-shadow:0 8px 18px rgba(199,155,85,.16)}
.brand-promise{margin:22px auto 76px;max-width:1260px;border-radius:32px;overflow:hidden;border:1px solid rgba(18,43,57,.08);box-shadow:0 28px 70px rgba(18,43,57,.08);background:
radial-gradient(circle at 12% 18%,rgba(255,255,255,.34),transparent 20%),
linear-gradient(110deg,#e5a082 0%,#f3c6a7 22%,#f4e6cc 50%,#b8dfdc 77%,#74b8b6 100%)}
.brand-promise-inner{padding:54px 58px;display:grid;grid-template-columns:.9fr 1.1fr;gap:48px;align-items:center;background:linear-gradient(90deg,rgba(255,253,248,.15),rgba(255,253,248,.58))}.brand-promise .eyebrow{color:#173b47}.brand-promise h2{max-width:540px;font-size:clamp(44px,5vw,72px)}.brand-promise p{font-size:17px;color:#304f59;max-width:620px}.brand-promise-sign{font-family:Georgia,'Times New Roman',serif;font-style:italic;font-size:28px;color:#825a31;margin-top:20px}.brand-promise-points{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.brand-promise-point{padding:20px;border-radius:18px;background:rgba(255,255,255,.58);border:1px solid rgba(255,255,255,.48);backdrop-filter:blur(10px)}.brand-promise-point strong{font-family:Georgia,'Times New Roman',serif;font-size:20px;font-weight:500}.brand-promise-point span{display:block;margin-top:5px;color:#49626a;font-size:13px}
.pricing{position:relative!important}.pricing:before{content:'';position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 50% 0%,rgba(232,197,133,.20),transparent 38%)}.plan{backdrop-filter:blur(12px);transition:.2s transform,.2s box-shadow}.plan:hover{transform:translateY(-5px);box-shadow:0 28px 72px rgba(18,43,57,.13)}.plan.featured{transform:scale(1.025)}.plan.featured:hover{transform:scale(1.025) translateY(-5px)}
@media(max-width:980px){.hero-actions{grid-template-columns:1fr!important}.brand-promise-inner{grid-template-columns:1fr}.brand-promise-points{grid-template-columns:1fr 1fr}.orb-stage{width:520px!important;height:520px!important}}
@media(max-width:640px){.hero{min-height:auto}.hero h1{font-size:54px!important}.hero-actions{grid-template-columns:1fr!important}.brand-promise{margin-left:18px;margin-right:18px}.brand-promise-inner{padding:36px 24px}.brand-promise-points{grid-template-columns:1fr}.orb-stage{width:390px!important;height:390px!important}}
</style>`;
function send(res,status,type,body,extra={}){res.writeHead(status,{...commonHeaders,'Content-Type':type,'Cache-Control':status===200?'no-store':'no-cache',...extra});res.end(body)}
function serveFile(req,res,filename,type){try{const body=fs.readFileSync(path.join(root,filename));if(req.method==='HEAD')return send(res,200,type,'');return send(res,200,type,body)}catch{return send(res,500,'text/plain; charset=utf-8','BrandedAlign is temporarily unavailable.')}}
function homepage(req,res){try{
let html=fs.readFileSync(path.join(root,'index-v2.html'),'utf8');
html=html.replace('</head>',launchStyles+'\n</head>')
.replace('brand review · clarity · confidence','BRAND REVIEW + COMPLIANCE')
.replace('<span class="eyebrow">Clarity before you publish</span>','<span class="eyebrow">Brand Review + Compliance</span>')
.replace('<h1>Protect your brand <span>before it goes live.</span></h1>','<h1>Protect your brand <span>before you publish.</span></h1>')
.replace('BrandedAlign helps you spot potential disclosure, accessibility, privacy, marketing, and brand-alignment risks across the places your business shows up.','Check one offer, website, or promotion for potential issues, or review how multiple offers work together under one brand.')
.replace(/<div class="hero-actions">[\s\S]*?<\/div>\s*<div class="hero-note">[\s\S]*?<\/div>/,`<div class="hero-actions"><a class="hero-choice" href="#fit"><span class="hero-choice-icon">♢</span><span><strong>Just Compliance</strong><small>Spot risks. Stay confident.</small></span></a><a class="hero-choice audit" href="#plans"><span class="hero-choice-icon">▥</span><span><strong>Full Brand Audit</strong><small>Review the whole ecosystem.</small></span></a><a class="hero-choice fit" href="#fit"><span class="hero-choice-icon">⌁</span><span><strong>60 Second Fit Check</strong><small>See where to start.</small></span></a></div>`)
.replace(/<div class="trust-band">[\s\S]*?<section class="section" id="how">/,`<div class="trust-band"><div class="container trust-row"><div class="trust-item"><span class="trust-icon">01</span><span><strong>One Brand</strong><br>Your foundation</span></div><div class="trust-item"><span class="trust-icon">02</span><span><strong>Multiple Offers</strong><br>All together</span></div><div class="trust-item"><span class="trust-icon">03</span><span><strong>Review</strong><br>Find what needs attention</span></div><div class="trust-item"><span class="trust-icon">04</span><span><strong>Clarify</strong><br>Get clear guidance</span></div><div class="trust-item"><span class="trust-icon">05</span><span><strong>Publish</strong><br>Move forward</span></div></div></div><section class="section" id="how">`)
.replace('<h2>From scattered brand pieces to one clear review.</h2>','<h2>Build with confidence.</h2>')
.replace('BrandedAlign is built for the messy real world where one person may have a website, affiliate offers, social content, lead magnets, and multiple income streams under the same name.','Review offers, websites, promotions, disclosures, and claims in one place so you can see potential risks before they go live.')
.replace('</section>\n\n  <section class="section" id="fit">',`</section><section class="brand-promise"><div class="brand-promise-inner"><div><span class="eyebrow">More than compliance</span><h2>Build with confidence.</h2><p>BrandedAlign helps you protect the bigger picture: your offers, your reputation, and the trust you are building around your brand.</p><div class="brand-promise-sign">Build with integrity. Share with purpose.</div></div><div class="brand-promise-points"><div class="brand-promise-point"><strong>See the whole ecosystem</strong><span>Review how websites, offers, disclosures, and content work together.</span></div><div class="brand-promise-point"><strong>Use safer language</strong><span>Get plain-language guidance without pretending automation is legal certification.</span></div><div class="brand-promise-point"><strong>Stay current</strong><span>Deep Dives keep important guidance visible and easier to understand.</span></div><div class="brand-promise-point"><strong>Keep judgment human</strong><span>BrandedAlign spots risk. You decide the next move.</span></div></div></div></section><section class="section" id="fit">`)
.replace('<h2>Choose the review capacity that fits your brand.</h2>','<h2>Choose Your Path.</h2>')
.replace('Secure checkout is hosted by Stripe. Paid access unlocks only after BrandedAlign receives and verifies the Stripe webhook.','Start focused, then grow the review capacity as your brand expands. Secure checkout is hosted by Stripe and paid access unlocks only after webhook verification.')
.replace('<div class="orb-labels"><span>Clearer</span><span>Safer</span><span>Stronger</span><span>Brighter</span></div>','')
.replace('<div class="purpose-note">Same<br>purpose.<br>A stronger<br>tomorrow.</div>','');
if(req.method==='HEAD')return send(res,200,'text/html; charset=utf-8','');return send(res,200,'text/html; charset=utf-8',html)}catch{return send(res,500,'text/plain; charset=utf-8','BrandedAlign is temporarily unavailable.')}}
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/health')return send(res,200,'application/json; charset=utf-8',JSON.stringify({ok:true,app:'BrandedAlign',owner:'TeamUpWithKrystal',version:'launch-luxury-v3',billing:'stripe-webhook-gated',deep_dives:true,auth_redirect:'production'}));if(req.method!=='GET'&&req.method!=='HEAD')return send(res,405,'text/plain; charset=utf-8','Method Not Allowed',{Allow:'GET, HEAD'});if(url.pathname==='/'||url.pathname==='/index.html')return homepage(req,res);if(url.pathname==='/styles-v2.css')return serveFile(req,res,'styles-v2.css','text/css; charset=utf-8');if(url.pathname==='/app-v2.js')return serveFile(req,res,'app-v2.js','application/javascript; charset=utf-8');if(url.pathname==='/orb-v2.js')return serveFile(req,res,'orb-v2.js','application/javascript; charset=utf-8');if(url.pathname==='/robots.txt')return send(res,200,'text/plain; charset=utf-8','User-agent: *\nAllow: /\n');return send(res,404,'text/plain; charset=utf-8','Not Found')});
server.listen(port,'0.0.0.0',()=>console.log('BrandedAlign luxury launch v3 active on '+port));